stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm i -D webpack-cli
    - npm i -D webpack
    - npm install
    - npm run build -- --output-path .
  tags:
    - wks-react
    - build
  only:
    - test
  artifacts:
    paths:
      - ./main.js
    when: on_success
    expire_in: 1d

deploy_staging:
  stage: deploy
  script:
    - mkdir -p ~/wks-django/wks/frontend/static/frontend
    - mkdir -p ~/wks_config
    - cp main.js ~/wks-django/wks/frontend/static/frontend
    - cp main.js ~/wks_config
  tags:
    - wks-react
    - deploy
  only:
    - test
